// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpvrhxtdahpjjanfcvse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdnJoeHRkYWhwamphbmZjdnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjU0MjQsImV4cCI6MjA2ODA0MTQyNH0.eb1OQ4gFhORN6wpkJUuIzgIJR5TOFFRDayfCIVTtMWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});